Fix lagrange multipliers with single basis LR basis
OPM/IFEM pull request #523
Opened 2021-12-21 18:09 UTC by akva2

plus a bugfix for second derivatives in 3D.

2021-12-21 18:10 UTC, akva2 commented
jenkins build this with downstreams ifem-stokes=190 please

2022-01-26 10:11 UTC, kmokstad requested changes
Looks fine, except for one issue that only will come to play when doing immersed boundaries with adaptive grids, I think (therefore not caught by any regression tests we have).

2022-01-26 10:20 UTC, akva2 commented on src/ASM/LR/ASMu2D.C
> +      LocalIntegral* A = integrand.getLocalIntegral(fe.N.size(),fe.iel);
This is borked indeed. And obviously not under testing.

2022-01-26 11:58 UTC, kmokstad approved these changes

2022-01-26 12:14 UTC, akva2 commented
jenkins build this with downstreams ifem-stokes=190 please

2022-01-26 12:35 UTC, merged